### ISSUE TITLE
Unit Tests Incorrect

### ISSUE THREAD

**Issue by kyleballard** [MarlabsInc/SocialGoal#13]
I'm not 100% if I am correct in this, but I believe some of the UnitTests are producing false positive results.

When CreateAsync() is called in the AccountController, it reaches into TestUserStore.FindAsync() and it always finds the user, so creation fails.  Changing this to something like:

```
    public Task<ApplicationUser> FindByNameAsync(string userName)
    {
        foreach (ApplicationUser user in _users.Values)
        {
            if (user.UserName == userName)
                return Task.FromResult(user);
        }
        return Task.FromResult<ApplicationUser>(null);
    }
```

Will produce different results.  The test LoginTest() succeeds because no user is created, and because user is null, RedirectToLocal is not called.   UrlHelper is null in RedirectToLocal when using the above FindByNameAsync method.

**Comment by shijuvar** [comment]
@kyleballard - Thanks for the feedback. We did a minor updated on the unit tests. We will refactor the existing unit tests on later. We encourage you to contribute for this project as we are taking pull requests.
