### ISSUE TITLE
Java Issues

### ISSUE THREAD

**Issue by ccocker** [MarlabsInc/SocialGoal#16]
Hi guys,

I have just downloaded application and tried to register a user and login.  When I do this I get alot of java issues

Unhandled exception at line 57, column 14 in http://localhost:5002/Scripts/jqplot.barRenderer.min.js

0x800a138f - JavaScript runtime error: Unable to set property 'BarRenderer' of undefined or null reference

Unhandled exception at line 57, column 14 in http://localhost:5002/Scripts/jqplot.dateAxisRenderer.min.js

0x800a138f - JavaScript runtime error: Unable to set property 'DateAxisRenderer' of undefined or null reference
Unhandled exception at line 57, column 14 in http://localhost:5002/Scripts/jqplot.categoryAxisRenderer.min.js

0x800a138f - JavaScript runtime error: Unable to set property 'CategoryAxisRenderer' of undefined or null reference
Unhandled exception at line 57, column 14 in http://localhost:5002/Scripts/jqplot.pointLabels.min.js

0x800a138f - JavaScript runtime error: Unable to set property 'PointLabels' of undefined or null reference
Unhandled exception at line 57, column 14 in http://localhost:5002/Scripts/jqplot.canvasTextRenderer.min.js

0x800a138f - JavaScript runtime error: Unable to set property 'CanvasTextRenderer' of undefined or null reference
Unhandled exception at line 57, column 14 in http://localhost:5002/Scripts/jqplot.canvasAxisTickRenderer.min.js

0x800a138f - JavaScript runtime error: Unable to set property 'CanvasAxisTickRenderer' of undefined or null reference
Unhandled exception at line 57, column 14 in http://localhost:5002/Scripts/jqplot.ohlcRenderer.min.js

0x800a138f - JavaScript runtime error: Unable to set property 'OHLCRenderer' of undefined or null reference
Unhandled exception at line 57, column 14 in http://localhost:5002/Scripts/jqplot.highlighter.min.js

0x800a138f - JavaScript runtime error: Unable to get property 'eventListenerHooks' of undefined or null reference

**Comment by ccocker** [comment]
It was issues with IE - I am using Google Chrome now and it works fine

**Comment by shijuvar** [comment]
It was a know issue in IE which is working fine on Chrome and Firefox.
