### ISSUE TITLE
Poor password management implementation

### ISSUE THREAD

**Issue by pbolduc** [MarlabsInc/SocialGoal#2]
Passwords are hashed using MD5 which is an extremely bad example to provide.  MD5 is considered a broken/banned algorithm by the SDL.

Banned Crypto and the SDL
http://blogs.msdn.com/b/sdl/archive/2009/07/16/banned-crypto-and-the-sdl.aspx

Better implementation uses a password based key derivation function (pbkdf2) and used in the new versions of the ASP.NET identity model.  See 

http://aspnetwebstack.codeplex.com/SourceControl/changeset/view/89b9166ca722#src/System.Web.Helpers/Crypto.cs

This implementation uses these key features:
1. a versioned hashed password.  Allows for migrating to newer versions or changing the algorithm over time
2. a salted hashed password
3. password that is hashed multiple times to increase hacking difficulty

A more extreme version of this algorithm can be found in the Thinktecture Identity server project:

https://github.com/thinktecture/Thinktecture.IdentityServer.v2/blob/master/src/Libraries/Thinktecture.IdentityServer.Core/Helper/CryptoHelper.cs

**Comment by shijuvar** [comment]
@pbolduc, 
Currently we are not using MD5 for passwords, and we are simply using ASP.NET Identity infrastructure.

**Comment by pbolduc** [comment]
Ok, I can see where I got confused.  In the following unused code https://github.com/MarlabsInc/SocialGoal/blob/master/source/SocialGoal.Service/UserService.cs  I can see:

```
   public ApplicationUser Login(string userName, string password)
    {
        var user = userRepository.Get(u => u.Email == userName);
        if (user != null && ValidatePassword(user, password)) return user;
        return null;
    }

    private bool ValidatePassword(ApplicationUser user, string password)
    {
        var encoded = Md5Encrypt.Md5EncryptPassword(password);
        return user.PasswordHash.Equals(encoded);
    }
```

This unused code should be removed.

**Comment by shijuvar** [comment]
Thanks @pbolduc. We have removed the unused code.
