### ISSUE TITLE
Md5EncryptPassword? 

### ISSUE THREAD

**Issue by ghost** [MarlabsInc/SocialGoal#3]
https://github.com/MarlabsInc/SocialGoal/blob/master/source/SocialGoal.Core/Common/Md5Encrypt.cs#L8-13

Seeing this code in place, i guess security is of no concern. And indeed, it is not explicitly listed as a goal of this project. But, md5(pass). Really? Might as well store the passwords as plain text...

**Comment by ghost** [comment]
O, heck. Someone beat me to it, but the issue was closed...

https://github.com/MarlabsInc/SocialGoal/issues/2

**Comment by shijuvar** [comment]
The project is not using MD5 for encrypting passwords and using ASP.NET Identity infrastructure for security. We have removed unused code from UserService.cs

**Comment by ghost** [comment]
Thumbs up! And thanks for distorting the discussion by deleting my last comment. What a joke.
