### ISSUE TITLE
Error while registering user

### ISSUE THREAD

**Issue by smsaxena19** [MarlabsInc/SocialGoal#4]
Hi 
issue is coming when i am registering my self in this application by putting username email and password.below is the error

Unhandled exception at line 57, column 14 in http://localhost:5002/Scripts/jqplot.barRenderer.min.js

0x800a138f - JavaScript runtime error: Unable to set property 'BarRenderer' of undefined or null reference

**Comment by shijuvar** [comment]
We have tested the app in modern versions of IE, Firefox and Chrome and were not able to find an issue while registering users

**Comment by smsaxena19** [comment]
Hi,

I am using VS2013. app gets build successfully in my vs and ran properly but after putting user info for registering and click on register but then the error comes i have attached the screen shot of the issue.if you c
![errpormvc5app](https://f.cloud.github.com/assets/6542268/2038474/d38e09ec-898e-11e3-938c-381a8ff26009.jpg)
an advise my something.
thanks

**Comment by shijuvar** [comment]
@smsaxena19,
It is unfortunate that you are having problems while register users. We could not reproduce this problem here, and even we had deployed the app in production environments.
