### ISSUE TITLE
Admin Dashboard

### ISSUE THREAD

**Issue by mvermef** [MarlabsInc/SocialGoal#7]
Appears to be missing controller/index, or index is corrupted, doesn't appear in your source tree, but does appear in the solution once downloaded and unzipped

**Comment by hoaitm** [comment]
I've got the same error with this request URL:  /Admin/Index

**Comment by shijuvar** [comment]
Currently, the app does not provide any admin specific user. All users can create their own goals and groups. Even there is not any admin controller. If there is any unnecessary code in the current code base, we will refactor it on the next cycle.
