### ISSUE TITLE
Profile

### ISSUE THREAD

**Issue by mvermef** [MarlabsInc/SocialGoal#8]
while logged in as Admin clicking profile yields null object - admin profile isn't created by default which causes issue.

Also appears to be some field duplication with Profile object, (username there and in IdentityUser (asp.net identity already has it it)), do really need it 2 times since you use it in the viewmodel for userprofile view.

**Comment by adarsh-vs** [comment]
Hi @mvermef ,
Thanks for pointing out the duplication of username property in userprofile model.  We have removed this property from userprofile.
Regarding Admin profile issue, we were using a predefined Admin user which was inserted as IdentityUser (didn't added to userprofile) through seed data when creating the DB.  This was creating the issue when accessing profile for Admin user (returns no userprofile).  Currently we have removed this predefined user.
